# Pensar Security Scan on Pull Request
# Runs a security scan whenever a pull request is opened or updated

name: Pensar Security Scan (PR)

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pensar CI
        run: npm install -g @pensar/ci

      - name: Run Pensar Security Scan
        env:
          PENSAR_API_KEY: ${{ secrets.PENSAR_API_KEY }}
          PENSAR_PROJECT_ID: ${{ secrets.PENSAR_PROJECT_ID }}
        run: pensar scan --branch ${{ github.head_ref }}
